Fix linux-sandbox actions being killed prematurely when using virtual threads (https://github.com/bazelbuild/bazel/pull/31017)
This is a version of https://github.com/bazelbuild/bazel/pull/29007 where the added test should pass for MacOS. The only change in this PR vs that PR is the location of `true` varies based on OS.

I think this should work, but I don't have a Mac handy to test this. If anyone has a Mac and can run `bazel test //src/test/java/com/google/devtools/build/lib/shell:JavaSubprocessFactoryTest` then that'd be much appreciated.

I forgot to account for the fact that MacOS places `true` at `/usr/bin/true` instead of `/bin/true`. This was the error during postsubmit from that test on MacOS:

```
1) createFromVirtualThreadForksOnPlatformThread(com.google.devtools.build.lib.shell.JavaSubprocessFactoryTest)
java.lang.AssertionError: Error running subprocess from virtual thread
	at com.google.devtools.build.lib.shell.JavaSubprocessFactoryTest.createFromVirtualThreadForksOnPlatformThread(JavaSubprocessFactoryTest.java:87)
	... 23 trimmed
Caused by: java.io.IOException: Cannot run program "/bin/true": Exec failed, error: 2 (No such file or directory)
```

Closes #31017.

PiperOrigin-RevId: 977850652
Change-Id: Ideba552c30cb0804c2e8722b31cbaf12c9beb077